version: "3.9"
services:
  app:
    build: .
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./config:/usr/local/bin/config
    command: ["/usr/local/bin/wait-for-it.sh", "db", "5432", "pandas-pouch"]

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: